CREATE TABLE [gsma].[ds_membership_data] (
    [id]                 INT             IDENTITY (1, 1) NOT NULL,
    [revision_id]        INT             NOT NULL,
    [revision]           DATETIME        NOT NULL,
    [organisation_id]    INT             NOT NULL,
    [group_id]           INT             NULL,
    [date]               DATETIME        NOT NULL,
    [date_type]          CHAR (1)        NOT NULL,
    [connections]        DECIMAL (22, 4) NULL,
    [connections_source] INT             NULL,
    [connections_tier]   TINYINT         NULL,
    [revenue]            DECIMAL (22, 4) NULL,
    [revenue_currency]   INT             NULL,
    [revenue_source]     INT             NULL,
    [revenue_attribute]  INT             NULL,
    [revenue_normalised] DECIMAL (22, 4) NULL,
    [revenue_tier]       TINYINT         NULL,
    [tier]               TINYINT         NULL,
    [votes]              INT             NULL,
    [votes_adjusted]     INT             NULL,
    [dues]               DECIMAL (22, 4) NULL,
    [dues_adjusted]      DECIMAL (22, 4) NULL,
    [dues_currency]      INT             NULL,
    [is_member]          BIT             NOT NULL,
    [is_special_case]    BIT             NOT NULL,
    [created_on]         DATETIME        NOT NULL,
    [created_by]         INT             NOT NULL,
    [last_update_on]     DATETIME        NOT NULL,
    [last_update_by]     INT             NOT NULL,
    CONSTRAINT [PK_ds_membership_data] PRIMARY KEY CLUSTERED ([id] ASC)
);

