CREATE TABLE [dbo].[_data_sets] (
    [id]                                   INT      IDENTITY (1, 1) NOT NULL,
    [metric_id]                            INT      NOT NULL,
    [attribute_id]                         INT      NULL,
    [type_id]                              INT      NULL,
    [default_date_type]                    CHAR (1) CONSTRAINT [DF_ds_data_sets_default_date_type] DEFAULT ('Q') NOT NULL,
    [is_live]                              BIT      NOT NULL,
    [is_live_for_organisation_data]        BIT      CONSTRAINT [DF_data_sets_is_live_for_organisation_data] DEFAULT ((0)) NOT NULL,
    [is_live_for_group_data]               BIT      CONSTRAINT [DF_data_sets_is_live_for_group_data] DEFAULT ((0)) NOT NULL,
    [is_live_for_country_data]             BIT      CONSTRAINT [DF_data_sets_is_live_for_country_data] DEFAULT ((0)) NOT NULL,
    [is_live_for_region_data]              BIT      CONSTRAINT [DF_data_sets_is_live_for_region_data] DEFAULT ((0)) NOT NULL,
    [is_aggregated]                        BIT      CONSTRAINT [DF_data_sets_is_aggregated] DEFAULT ((0)) NOT NULL,
    [is_aggregated_from_organisation_data] BIT      CONSTRAINT [DF_data_sets_is_aggregated_from_organisation_data] DEFAULT ((0)) NOT NULL,
    [is_aggregated_from_zone_data]         BIT      CONSTRAINT [DF_data_sets_aggregate_from_zones] DEFAULT ((0)) NOT NULL,
    [has_forecasts]                        BIT      CONSTRAINT [DF_ds_data_sets_has_forecasts] DEFAULT ((0)) NOT NULL,
    [has_organisation_data]                BIT      CONSTRAINT [DF_ds_data_sets_has_organisation_data] DEFAULT ((1)) NOT NULL,
    [has_group_data]                       BIT      CONSTRAINT [DF_ds_data_sets_has_group_data] DEFAULT ((0)) NOT NULL,
    [has_country_data]                     BIT      CONSTRAINT [DF_ds_data_sets_has_country_data] DEFAULT ((0)) NOT NULL,
    [has_region_data]                      BIT      CONSTRAINT [DF_ds_data_sets_has_regional_data] DEFAULT ((0)) NOT NULL,
    [has_organisation_rank]                BIT      CONSTRAINT [DF_ds_data_sets_has_organisation_rank] DEFAULT ((0)) NOT NULL,
    [has_group_rank]                       BIT      CONSTRAINT [DF_ds_data_sets_has_group_rank] DEFAULT ((0)) NOT NULL,
    [has_country_rank]                     BIT      CONSTRAINT [DF_ds_data_sets_has_country_rank] DEFAULT ((0)) NOT NULL,
    [has_region_rank]                      BIT      CONSTRAINT [DF_ds_data_sets_has_region_rank] DEFAULT ((0)) NOT NULL,
    [show_in_metrics_only]                 BIT      CONSTRAINT [DF_data_sets_metrics_only] DEFAULT ((0)) NOT NULL,
    [created_on]                           DATETIME CONSTRAINT [DF_ds_data_sets_created_on] DEFAULT (getdate()) NOT NULL,
    [created_by]                           INT      CONSTRAINT [DF_ds_data_sets_created_by] DEFAULT ((0)) NOT NULL,
    [super_set_base]                       BIT      DEFAULT ((0)) NOT NULL,
    [web_set_base]                         BIT      NOT NULL,
    [super_set_base_zones]                 BIT      DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_data_sets] PRIMARY KEY CLUSTERED ([id] ASC)
);

