CREATE TABLE [dbo].[auctions] (
    [id]                    INT             IDENTITY (1, 1) NOT NULL,
    [zone_id]               INT             NOT NULL,
    [status_id]             INT             NOT NULL,
    [type_id]               INT             NOT NULL,
    [date]                  DATETIME        NULL,
    [date_type]             CHAR (1)        CONSTRAINT [DF_auctions_date_type] DEFAULT ('M') NULL,
    [block]                 DECIMAL (22, 4) NULL,
    [block_paired]          DECIMAL (22, 4) NULL,
    [block_unpaired]        DECIMAL (22, 4) NULL,
    [downlink_band]         NVARCHAR (MAX)  NULL,
    [uplink_band]           NVARCHAR (MAX)  NULL,
    [note]                  NVARCHAR (MAX)  NULL,
    [obligations]           NVARCHAR (MAX)  NULL,
    [terms]                 NVARCHAR (MAX)  NULL,
    [applicants]            INT             NULL,
    [bidders]               INT             NULL,
    [winners]               INT             NULL,
    [price]                 DECIMAL (22, 4) NULL,
    [price_usd]             DECIMAL (22, 4) NULL,
    [price_per_mhz]         DECIMAL (22, 4) NULL,
    [price_per_mhz_usd]     DECIMAL (22, 4) NULL,
    [price_per_mhz_usd_ppp] DECIMAL (22, 4) NULL,
    [price_currency_id]     INT             NULL,
    [reserve]               DECIMAL (22, 4) NULL,
    [reserve_currency_id]   INT             NULL,
    [created_on]            DATETIME        CONSTRAINT [DF_auctions_created_on] DEFAULT (getdate()) NOT NULL,
    [created_by]            INT             CONSTRAINT [DF_auctions_created_by] DEFAULT ((0)) NOT NULL,
    [last_update_on]        DATETIME        CONSTRAINT [DF_auctions_last_update_on] DEFAULT (getdate()) NOT NULL,
    [last_update_by]        INT             CONSTRAINT [DF_auctions_last_update_by] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_auctions] PRIMARY KEY CLUSTERED ([id] ASC)
);

