CREATE TABLE [dbo].[documents_tmp] (
    [id]                    INT             IDENTITY (1, 1) NOT NULL,
    [title]                 NVARCHAR (512)  NOT NULL,
    [subtitle]              NVARCHAR (512)  NULL,
    [summary]               NVARCHAR (MAX)  NULL,
    [file]                  NVARCHAR (256)  NOT NULL,
    [file_extension]        NVARCHAR (32)   NOT NULL,
    [file_mime_type]        NVARCHAR (128)  NULL,
    [file_pages]            INT             NULL,
    [file_size]             INT             NULL,
    [hash]                  VARCHAR (64)    NULL,
    [status]                BIT             NOT NULL,
    [source]                NVARCHAR (64)   NULL,
    [source_id]             INT             NULL,
    [source_slug]           NVARCHAR (64)   NULL,
    [source_url]            NVARCHAR (1024) NULL,
    [has_image]             BIT             NOT NULL,
    [thumbnail_width]       INT             NULL,
    [thumbnail_height]      INT             NULL,
    [is_featured]           BIT             NOT NULL,
    [is_hidden]             BIT             NOT NULL,
    [is_private]            BIT             NOT NULL,
    [requires_subscription] BIT             NOT NULL,
    [published_on]          DATETIME        NOT NULL,
    [created_on]            DATETIME        NOT NULL,
    [created_by]            INT             NOT NULL,
    [last_update_on]        DATETIME        NOT NULL,
    [last_update_by]        INT             NOT NULL
);

