CREATE TABLE [dbo].[documents] (
    [id]                    INT             IDENTITY (1, 1) NOT NULL,
    [title]                 NVARCHAR (512)  NOT NULL,
    [subtitle]              NVARCHAR (512)  NULL,
    [summary]               NVARCHAR (MAX)  NULL,
    [file]                  NVARCHAR (256)  NOT NULL,
    [file_extension]        NVARCHAR (32)   CONSTRAINT [DF_documents_file_extension] DEFAULT (N'pdf') NOT NULL,
    [file_mime_type]        NVARCHAR (128)  CONSTRAINT [DF_documents_file_mime_type] DEFAULT (N'application/pdf') NULL,
    [file_pages]            INT             NULL,
    [file_size]             INT             NULL,
    [hash]                  VARCHAR (64)    NULL,
    [status]                BIT             CONSTRAINT [DF_documents_status] DEFAULT ((0)) NOT NULL,
    [source]                NVARCHAR (64)   NULL,
    [source_id]             INT             NULL,
    [source_slug]           NVARCHAR (64)   NULL,
    [source_url]            NVARCHAR (1024) NULL,
    [has_image]             BIT             CONSTRAINT [DF_documents_has_image] DEFAULT ((0)) NOT NULL,
    [thumbnail_width]       INT             NULL,
    [thumbnail_height]      INT             NULL,
    [is_featured]           BIT             CONSTRAINT [DF_documents_is_featured] DEFAULT ((0)) NOT NULL,
    [is_hidden]             BIT             CONSTRAINT [DF_documents_is_hidden] DEFAULT ((0)) NOT NULL,
    [is_private]            BIT             CONSTRAINT [DF_documents_is_private] DEFAULT ((0)) NOT NULL,
    [requires_subscription] BIT             CONSTRAINT [DF_documents_is_subscription] DEFAULT ((0)) NOT NULL,
    [published_on]          DATETIME        DEFAULT (getdate()) NOT NULL,
    [created_on]            DATETIME        CONSTRAINT [DF_documents_created_on] DEFAULT (getdate()) NOT NULL,
    [created_by]            INT             CONSTRAINT [DF_documents_created_by] DEFAULT ((0)) NOT NULL,
    [last_update_on]        DATETIME        CONSTRAINT [DF_documents_last_update_on] DEFAULT (getdate()) NOT NULL,
    [last_update_by]        INT             CONSTRAINT [DF_documents_last_update_by] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_documents] PRIMARY KEY CLUSTERED ([id] ASC)
);

