CREATE VIEW [dbo].[dc_group_data] AS select 
[id]
      ,[organisation_id]
      ,[ownership_threshold]
      ,[metric_id]
      ,[metric_order]
      ,[attribute_id]
      ,[attribute_order]
      ,[date]
      ,[date_type]
      ,[val_d]
      ,[val_i]
      ,[currency_id]
      ,[source_id]
      ,[confidence_id]
      ,[definition_id]
      ,[has_flags]
      ,[is_calculated]
      ,[is_proportionate]
      ,[is_spot]
      ,[flags]
      ,[location]
      ,[last_update_on]
      ,[last_update_by]
  FROM [wi_master].[dbo].[dc_group_data_val_sum]


union all

select 
[id]
      ,[organisation_id]
      ,[ownership_threshold]
      ,[metric_id]
      ,[metric_order]
      ,[attribute_id]
      ,[attribute_order]
      ,[date]
      ,[date_type]
      ,[val_d]
      ,[val_i]
      ,[currency_id]
      ,[source_id]
      ,[confidence_id]
      ,[definition_id]
      ,[has_flags]
      ,[is_calculated]
      ,[is_proportionate]
      ,[is_spot]
      ,[flags]
      ,[location]
      ,[last_update_on]
      ,[last_update_by]
  FROM [wi_master].[dbo].[dc_group_data_val_proportionate];
